name: Actions for ci/cd lifecycle
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  jest:
    name: Jest testing
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/Checkout@v2
      - name: Install packages
        run: npm ci
        env:
          CI: true
      - name: Run tests
        run: npm t
